### ISSUE TITLE
What is Gender? Spanish Translation

### ISSUE THREAD

**Issue by VencesMA** [GenderDysphoria/GenderDysphoria.fyi#10]
### ¿Qué es el Género?

Si trazas la etimología de la palabra a sus raíces latinas, género simplemente significa “tipo”. Históricamente, la palabra fue utilizada en literatura para referirse a los sustantivos masculinos, femeninos y neutros. En 1955 el psicólogo John Money propuso usar el término para diferenciar al sexo mental del sexo físico, pero no fue el primero en hacerlo.

El Sexo humano (el adjetivo, no el verbo) se divide en tres categorías:

- **Genotipo**: El cariotipo cromosómico definido genéticamente de un organismo (XX, XY, y [todas las variantes que hay](https://twitter.com/sciencevet2/status/1035250518870900737?lang=en))
- **Fenotipo**: Las características sexuales primarias y secundarias observables (genitales, distribución adiposa y muscular, estructura ósea, etc.)
- **Género**: El modelo interno mental del propio sexo de una persona.

![bimodal-0e3e9b4bc1](https://user-images.githubusercontent.com/63420535/79053523-b57f8200-7c03-11ea-8a3e-d63ce1adac08.png)

Cualquiera de estos aspectos puede caer en una posición o en un rango de valores. En tu clase de salud de educación básica probablemente te enseñaron que tu Genotipo es binario, o Femenino (XX) o Masculino (XY), cuando en realidad hay más de una docena de otras permutaciones que pueden ocurrir en los seres humanos.

De la misma forma, muchas personas creen que el Fenotipo también es binario, pero la biología ha reconocido por cientos de años que cuando trazas todas las características sexuales a lo largo de una población, en realidad terminas con una distribución bimodal donde la mayoría de la población cae dentro de un percentil de dos grupos. Esto significa que algunas personas, simplemente por la naturaleza de cómo funciona la vida, caen fuera de los dos montones típicos. Mucha gente cae en el medio, con características de ambos sexos.

El género, sin embargo, es mucho más… enredado y complicado. Hay muchas formas diferentes en que la gente ha intentado ilustrar el espectro de género, pero ninguna ha podido capturarlo por completo, debido a que el espectro es en sí un concepto bastante abstracto.

La versión corta es, algunas personas son hombres, algunas son mujeres, algunas no sienten ningún género en lo absoluto, algunas sienten ambos, algunas están en el medio, algunas caen en los bordes. Otres oscilan a lo largo de todo el espectro de maneras impredecibles, cambiando como el viento. Solo un individuo puede identificar su propio género, nadie más se los puede dictar.

El género es en parte un constructo social, en parte comportamientos aprendidos, y en parte procesos biológicos que se forman muy temprano en la vida de una persona.

La evidencia presente parece sugerir que el género de una persona se establece durante la gestación, mientras la certeza cerebral se está formando (más al respecto en la sección Causas de la Disforia de Género). Este modelo mental luego informa, a un nivel subconsciente, a qué aspectos del espectro de género se inclinará una persona. Afecta el comportamiento, la percepción del mundo, la forma en que se experimenta la atracción (separado de la orientación sexual y la influencia de hormonas) y como nos relacionamos con otras personas.

El género también afecta las expectativas que el cerebro tiene para el ambiente en el que reside (tu cuerpo), y cuando ese ambiente no cumple esas expectativas, el cerebro manda señales de alarma en la forma de depresión, despersonalización, desrealización y disociación. Estas son las formas subconscientes del cerebro de informarnos que algo está muy mal.

En el lado social, el género involucra la presentación, cómo nos comunicamos, cuáles son nuestras expectativas de la vida, y los roles que cumplimos en nuestro paso por la vida. Todos estos son aspectos culturales, cosas que se han desarrollado dentro de la población a lo largo del tiempo, pero que a pesar de ser esencialmente “inventados”, siguen estando conectados a la identidad de género. Una persona suele conectar a los aspectos sociales de su género interno, sin siquiera darse cuenta de que lo hace, y cuando se les niega el acceso a estos aspectos sociales, esto resulta en incomodidad con su posición social en la vida.

El experimento de John Money intentó confirmar su creencia de que el género es un constructo enteramente social, y que cualquier niñx puede ser criado para creerse lo que se le enseñe ser. Su experimento fue un fracaso absoluto (ver la sección Disforia Bioquímica). El género no cambia, cada humano tiene el mismo género a los 40 que a los 4 años. Lo que cambia es nuestro entendimiento personal de nuestro género mientras maduramos como individuos.

Estos síntomas negativos (depresión, desrealización, incomodidad social) son los síntomas de la Disforia de Género.

Lo que el **Género *no* es**, es orientación sexual. Describimos la orientación en términos relativos al género de unx mismx (homosexual/heterosexual/bisexual), pero el género en sí mismo no afecta la sexualidad, y la sexualidad no tiene rol en el género.

En términos generales este ensayo describirá al género en un sentido binario de identidades (masculinas/femeninas) frente a identidades no binarias (agénero, bigénero, genderqueer, etc.), pero esto es únicamente por simplicidad de escritura. Por favor ten en cuenta que la profundidad de la experiencia y expresión de género es mucho, mucho más complicada que este simple análisis.

**Comment by Twipped** [comment]
Content installed into public/gdb/es/what-is-gender.md
