### ISSUE TITLE
The History of Gender Dysphoria Spanish Translation

### ISSUE THREAD

**Issue by VencesMA** [GenderDysphoria/GenderDysphoria.fyi#11]
### Una Breve Historia de la Disforia de Género

En 1984 el destacado sexólogo Dr. Alfred Kinsey (sí, [*ese* Kinsey](https://es.wikipedia.org/wiki/Alfred_C._Kinsey)) fue contactado por una mujer cuyo hijo varón insistía con rotundidad que era de hecho una niña, y que algo había salido muy mal. La madre, en lugar de intentar suprimir a su hija, deseaba ayudarla a convertirse en quien ella sabía que era. Kinsey contactó a un endocrinólogo alemán llamado [Dr. Harry Benjamin](https://es.wikipedia.org/wiki/Harry_Benjamin) para ver si él podía ayudar a la niña. El Dr. Benjamin desarrolló un protocolo de terapia de estrógenos para la adolescente, y trabajó con la familia para encontrar ayuda quirúrgica.

Benjamin después continuó refinando su protocolo y trató a miles de pacientes con sentimientos similares durante el curso de su carrera. Él se rehusó a aceptar algún pago por su trabajo, quedando en cambio satisfecho con el alivio que les proporcionaba a estos pacientes, y usando su tratamiento para aumentar su comprensión sobre la condición. Él acuñó un término para este sentimiento de incongruencia en 1973: Disforia de Género. Desafortunadamente, este término no sería usado en los Estados Unidos hasta el 2013, ya que la Asociación Estadounidense de Psiquiatría optó en su lugar por el término Desorden de Identidad de Género.

{!{ {{inject '~/img' images.hbscale className="card sideline" caption="Harry Benjamin Diagnostic Scale"}} }!}

Si eres una persona trans leyendo esto, puede que hayas escuchado el nombre de Harry Benjamin antes, pero probablemente no en un contexto favorable. En 1979 su nombre fue usado (sin su permiso) en la formación de la Asociación Internacional de la Disforia de Género Harry Benjamin (HBIGDA), que publicó sus Estándares de Cuidado (SoC) para las personas transgénero. Estos SoC se llegaron a conocer como las Reglas de Harry Benjamin, y fueron infámes por ser limitantes respecto a cómo se podía diagnosticar la Disforia de Género. Los pacientes eran colocados dentro de una escala de seis categorías basadas en su nivel de miseria y disfunción sexual. Si no caías dentro de la Categoría 5 o superior, clasificada como “Verdadero Transexual”, usualmente eras rechazado del tratamiento.

El problema era que, las Categorías 5 y 6 requerían que estuvieras exclusivamente atraídx a tu propio sexo de nacimiento. La transición tenía que hacerte heterosexual, no homosexual, y lxs bisexuales no estaban permitidxs. También tenías que experimentar una angustia severa con tu cuerpo y genitales, y ya estar viviendo como tu verdadero género sin el tratamiento. Muchas personas trans le daban la vuelta a estas limitaciones mediante entrenamiento comunitario y presentaciones performativas, pero para muchas personas (yo incluída) se creía que si no encajabas dentro de todos los criterios, entonces no eras lo suficientemente trans para transicionar.

En 2011 la HBIGDA se reorganizó para responder a la creciente presión de la aceptación y entendimiento de las personas trans, tomando el nuevo nombre de Asociación Profesional Mundial para la Salud del Transgénero (WPATH). Bajo la guía de verdaderas personas transgénero (por primera vez en la organización), la WPATH procedió a publicar enteramente nuevos Estándares de Cuidado (SoC, versión 7, la primera en diez años) que abandonó la Escala Benjamin, enfocándose en los síntomas específicos individuales y desconectando el género de la sexualidad por completo. Dos años más tarde, en 2013, la Asociación Estadounidense de Psiquiatría cambió su criterio de diagnóstico para empatar con los Soc de la WPATH en su Manual Diagnóstico y Estadístico de los Trastornos Mentales (DSM) versión 5, reemplazando el Desorden de Identidad de Género con Disforia de Género. Con este cambio, las transiciones quedaron disponibles para todas las personas trans en los Estados Unidos.

Esta es la razón de que la presencia trans alrededor del mundo ha explotado repentinamente en la última década. Con un acceso más fácil vienen números más grandes, con números más grandes viene más visibilidad, con más visibilidad viene mas conciencia, y con más conciencia se obtienen más personas accediendo a un tratamiento. [Un estudio realizado en 2014](https://williamsinstitute.law.ucla.edu/wp-content/uploads/TransAgeReport.pdf) mostró que el 0.6% de adultos y el 0.7% de jóvenes en los Estados Unidos se identificaba como trasngénero, [un estudio conducido en 2016](https://www.cdc.gov/mmwr/volumes/68/wr/mm6803a3.htm) mostró que el 1.8% de estudiantes en edad de secundaria y bachillerato se identificaba como transgénero, y [una encuesta conducida por GLAAD en 2017](https://www.glaad.org/files/aa/2017_GLAAD_Accelerating_Acceptance.pdf) mostró un asombroso 12% de encuestados de entre 18 a 34 años que no se identificaban como cisgénero.

Las personas transgénero están saliendo del clóset, estamos en todas partes.

#### Entonces, ¿Qué Es la Disforia de Género?

> **Dis·fo·ria** - *Sustantivo*   
> Un estado de inquietud o disatsfacción generalizada con la vida. Lo opuesto a la euforia.

{!{ {{inject '~/img' images.glue className="card sideline" caption="What Dysphoria Feels Like"}} }!}

Hay un malentendido común entre personas tanto cisgénero como transgénero de que la Disforia de Género se refiere exclusivamente a la incomodidad física con el propio cuerpo. Sin embargo, esta creencia de que la incomodidad del cuerpo es central a la Disforia de Género es de hecho errónea, y no es ni siquiera un componente mayoritario en el diagnóstico de la Disforia de Género. La Disforia de Género atraviesa un gran número de aspectos de la vida, incluyendo cómo interactúas con otros, cómo otros interactúan contigo, cómo te vistes, cómo te comportas, cómo encajas en la sociedad, cómo percibes el mundo a tu alrededor, y sí, cómo te relaciones con tu cuerpo. Consecuentemente, proponentes de los SoC 7 de la WPATH y el DSM-5, han tomado el hábito de decir que no necesitas tener disforia para ser transgénero. Esta afirmación es repetida frecuentemente como un mantra, pues informa a las personas que no sienten una incomodidad significativa con su cuerpo que también podrían ser transgénero.

En principio, la Disforia de Género es un sentimiento de incongruencia intrínseca al ser. No hay lógica detrás de esta incongruencia, no hay nada que lo explique, y no puedes describir porqué te sientes de esta manera, solo está ahí. Las cosas en tu existencia son incorrectas, e incluso saber qué cosas son incorrectas puede ser difícil de identificar apropiadamente.

Evey Winters lo describió muy acertadamente [en su publicación sobre Disforia](https://eveywinters.com/2019/10/14/on-dysphoria-before-enduring-and-after/).

> ¿Alguna vez has estado sentadx en un lugar público o un sitio formal y de repente la planta de tu pie te empieza a picar? No es como que pudieras quitarte los zapatos ahí mismo y rascarte, así que aguantas el sentimiento de morir por dentro mientras la picazón crece y crece hasta que estás listx para asesinar a la persona más cercana que se dirija a ti.
>
> O cuando era más joven, solía ver televisión por cable en las mañanas antes de la escuela. Como era TV por cable en la Virginia del Oeste rural a principios de los 90’s, cada tanto cambiaba a mi canal favorito para ver mis programas mientras comía mi avena con maple y estaría viendo los Power Rangers – pero el audio venía de otra estación (usualmente el canal del tiempo). El video estaba bien. El audio estaba bien. ¿Pero la discordancia entre los dos? Ese es el tipo de frustración que como niñx se queda contigo todo el día.
>
> Es el sentimiento que tienes cuando pides una refrescante Coca de dieta y el mesero dice, “¿Pepsi está bien?"
>
> Es saber que algo está mal y no ser capaz de hacer una maldita cosa al respecto.

La manera en que yo solía describirlo era como usar guantes de adulto cuando eres niño. Puedes meter tu mano en el guante, y tus dedos caben en los orificios del guante, pero tu destreza con los guantes está seriamente obstaculizada. Puedes ser capaz de tomar y levantar algo, pero no lo puedes manipular como un adulto lo haría. Las cosas sencillamente no están bien.

La Disforia de Género, en su núcleo, es simplemente reacciones del cerebro que sabe que algo no encaja. Esta incongruencia es tan profunda dentro de los subsistemas del cerebro que no hay un mensaje obvio de cuál es el problema. La única forma de identificarlo es por medio de las emociones que desencadena. Nuestra consciencia recibe retroalimentación positiva (euforia) o negativa (disforia) de acuerdo a qué tan bien nuestro ambiente se alinea con nuestro sentido interno del ser. Parte de la transición es aprender a reconocer estas señales.

Las personas cisgénero las reciben también, pero dado que las señales usualmente se alinean con su ambiente, lo dan por sentado. Hay, sin embargo, algunas excepciones notables en las que una persona cisgénero ha sido [puesta en una situación](https://grazia.mx/maisie-williams-siente-que-arya-stark-le-causo-problemas-con-su-imagen-corporal/) en la que experimenta disforia de género. Intentos de criar niñxs cisgénero [como del sexo opuesto](https://www.reporteindigo.com/piensa/la-tragica-reasignacion-de-sexo-de-bruce-reimer/) (advertencia de contenido sobre suicidio) siempre se han encontrado con el fracaso cuando el niñx inevitablemente se declara a sí mismo de forma diferente.

Estos impulsos de euforia y disforia, excitación y aversión, todos se manifiestan de distintas formas, algunas obvias, otras mucho más sutiles. La Disforia, además, cambia a lo largo del tiempo, tomando nuevas formas conforme uno se mueve de la preconciencia al entendimiento y a través de la transición. La meta de este ensayo es desglosar estas manifestaciones en sus distintas categorías y describirlas de modo que otrxs puedan aprender a reconocerlas. Esta publicación es bastante larga, por lo que la he separado en múltiples páginas.

Sin embargo, primero debo enfatizar algo muy importante. Tan importante que lo estoy poniendo en letras mayúsculas y en negritas.

**CADA PERSONA TRANS EXPERIMENTA UN DIFERENTE CONJUNTO DE FUENTES DE DISFORIA Y EN DIFERENTES INTENSIDADES**

No hay solo una experiencia trans, no hay un conjunto estándar de sentimientos e incomodidades, no hay *una verdadera narrativa trans*. Cada persona experimenta la disforia a su propia manera y en su propio grado, y lo que molesta a una persona puede no afectarle a otra.

Bien, con esta aclaración fuera del camino, vayamos al grano.

**Comment by Twipped** [comment]
Content installed into public/gdb/es/history.md
