### ISSUE TITLE
Node 16/18 migration

### ISSUE THREAD

**Issue by astralfrontier** [GenderDysphoria/GenderDysphoria.fyi#116]
Upgrade the site to use Node major version 16/18.

- The engine version in `package.json` should be updated appropriately
- An `.nvmrc` file at the root should exist to let users know which specific version to use
- Generated HTML & file structure should match the Node 14 version

**Comment by astralfrontier** [comment]
I'm working on this via a fork here: https://github.com/astralfrontier/GenderDysphoria.fyi/tree/node-16

Currently the site does not build properly. I'm working on tracking that down.

**Comment by astralfrontier** [comment]
some notes on what I did:
- git clone blah blah
- I decided to target Node 16 rather than jump right to 18 for a wider window of compatibility. So 'nvm install 16 --lts'  gave me the binary I wanted. I added an .nvmrc file to my fork as well
- Next, 'npm install'. It didn't hang forever, but eventually balked on building scss
- Next, 'npx npm-check-updates -u' to update dependencies b/c the errors looked like API changes
- Next, roll back individual updates w/ dependency conflicts

The biggest offenders were the rollup plugins. Once the site builds properly under Node 16, I feel like addressing the warnings from 'npm install' will be fruitful (e.g. I saw a couple packages saying they'd moved to a new address). After that, moving to Node 18 will probably be more of the same.

**Comment by alliejones** [comment]
👋🏻 Here from our Mastodon discussion. Anything in particular you're stuck on or that I can help by taking a look at?

**Comment by astralfrontier** [comment]
This is where I left off: https://github.com/GenderDysphoria/GenderDysphoria.fyi/commit/0cfd6c798b6f2733d39908f2329e87763fef1f6f

Somewhere along the line, the "html" variable is being populated by a Promise, rather than a string. That means all the processing happening to it is failing. So the next step is find out where that Promise is returned, and put the "await" there so we can get the string we need.

**Comment by astralfrontier** [comment]
I added you as a collaborator on my fork so you should be able to work directly on what I've got, rather than doing yet another fork.

**Comment by alliejones** [comment]
@astralfrontier It looks to me like `html` is a promise because of the `shrink` helper function on line 135 in the same file; `minify` from `html-minifier-terser` returns a promise. The smallest change is probably to `await` on line 149, since that will avoid making any changes to the error handling:
```js
try {
      html = await shrink(html);
    } catch (e) {
      e.message = `Error while minifying page "${
        page.input
      }": ${e.message.slice(0, 50)}`;
      throw e;
    }
```
Didn't make a commit with this to your branch since it's tiny.

Other than this, it seems like you've pretty much got the Node 16 upgrade working? `gulp uat` works for me with no errors (though I haven't done a diff with the previous version output or anything).

**Comment by astralfrontier** [comment]
Yeah, gulp works with no errors. Moving await to the shrink() call didn't fix the underlying problem that Handlebars still isn't working, unfortunately, but you found the right place for the await :)

Onward!

**Comment by astralfrontier** [comment]
So I've been following the Github workflow steps to verify that the site is building properly. But just in case, I went back to the master branch, installed Node 14, and.... I see the same thing when I look at index.html? `gulp uat` shows me a fully functional site, on the other hand. So we might be closer than I thought.
Last step is to mirror the Node 14 site locally, then mirror the update, and check for discrepancies.

**Comment by astralfrontier** [comment]
PR is open, anyone who's interested can review it

**Comment by Artanicus** [comment]
Adding some notes on testing I did to confirm site was functional in a repeatable environment.

Goal was to run `gulp uat` on a fresh debian bullseye container with node 16.x.

Repeatable testing steps:
```
%> docker run -it --rm -p 1234:8000 -v $(pwd):/srv -w="/srv/src/resource" ghcr.io/artanicus/gulp:16 uat            
```

(had to fork a gulp image as all the existing ones were horribly out of date. ghcr.io/artanicus/gulp:18 also exists.)
