### ISSUE TITLE
Gender Euphoria Spanish Translation

### ISSUE THREAD

**Issue by VencesMA** [GenderDysphoria/GenderDysphoria.fyi#12]
### Euforia de Género

Antes de que pueda empezar a hablar sobre la incomodidad, tengo que hablar sobre el alivio. La Euforia de Género es en sí misma un signo de Disforia de Género. Puedes estar preguntándote. “¿cómo puede la felicidad ser tristeza?” La respuesta a eso es simple.

Imagina a una persona que nació en una cueva, que pasó su vida entera viviendo bajo tierra, cuya única fuente de iluminación eran velas y lámparas de aceite. Imagina que nunca ha estado afuera en la superficie, que ni siquiera sabe que la superficie existe. Luego, un día, ocurre un derrumbe en un túnel secundario que revela una apertura a la superficie. La luz del sol se cuela por el orificio, y al inicio es cegadora y la persona huye atemorizada. Más tarde regresa a la apertura, y cuando los ojos de la persona se adaptan, miran a través del agujero y ven un mundo luminoso y brillante lleno de colores que ni siquiera sabía que existía.

Ese mundo da miedo, es enorme y lleno de misterios, así que se arrastra de regreso a la cueva por seguridad, pero ese agujero sigue ahí, y ve la luz cada vez que pasa a su lado. Gradualmente se asoma más y con mayor frecuencia, y cada vez más lejos de la apertura. Empieza a desear esa luz, a encontrar razones para visitarla con mayor frecuencia.

Eventualmente, se da cuenta que ya no quiere regresar a la cueva. Tiene que volver, porque su familia y amigos están ahí, pero este lugar es mucho mejor, se quiere quedar aquí. Ir de vuelta a la cueva se siente mal, estar en la oscuridad empieza a doler tanto.

Así es la Euforia de Género, son breves destellos de luz que pueden ser muy luminosos para manejar al inicio, muy confusos de entender, pero que conforme el tiempo pasa, te acostumbras más a ellos y te das cuenta de que ahí es a donde perteneces, y la oscuridad se vuelve la disforia.
Muchas personas trans no tienen idea de en cuánto dolor se encuentran hasta que hallan un poco de alivio. Cosplay, actuación en escenarios, drag, juegos de rol, videojuegos; pequeñas incursiones a un género diferente del que han vivido. Encuentran que se siente un poco más cómodo. Hacen excusas del porqué (“Si voy a estarle viendo el trasero a este personaje, mejor que sea el trasero de una chica.”), se tratan de convencer a sí mismxs de que todo es por diversión, o una expresión artística. Se pueden decir a sí mismxs que los momentos de alegría que sienten escuchando un pronombre diferente son solo por novedad. Pero pronto se encuentran buscando razones para hacer con mayor frecuencia. Más y más seguido juegan con personajes de un sexo diferente, realizan más disfraces, compran más ropa, actúan más seguido. Te encuentras a ti mismx deseando hacer eso todo el tiempo, porque se siente mejor que tu vida real, y ser “tú” empieza a doler. Eventualmente, el viejo tú se convierte en el disfraz.

Esta es la razón más fundamental por la que en nuestra comunidad decimos “no necesitas tener disforia para ser trans”, porque la tinta negra en un lienzo negro no es visible sin una examinación cercana y mucha luz.

Cualquier cosa que puede ser una fuente de disforia tiene su contraparte de euforia.

Ejemplos:

- Ser tratado del género correcto
- Ser llamado por el nombre que elegiste
- Usar ropa de tu género
- Ver y sentir cambios en tu cuerpo
- Verte a ti mismx en el espejo (remoción de la despersonalización)
- Socializar en modos que se conforman con las expectativas de género
- Obtener un corte de cabello masculino / femenino / andrógino
- Depilar tus piernas
- NO depilar tus piernas
- Ser incluidx en algo que normalmente no lo serías por el género que te asignaron al nacer (ej., una despedida de soltera o una despedida de soltero)
- Sentirse sexy / tener sexo de una forma que se alinea con tu género y sexualidad.
- Incluso simplemente estar afuera en el mundo como tú mismx y ser visto como tú mismx puede ser sumamente eufórico.

**Lo que la euforia NO es**, es un subidón sexual, excitación o fetiche. Algunas veces la euforia puede disparar una respuesta sexual, y hay muchos factores en juego que lo causan (sentirte bien sobre tu cuerpo puede prenderte, por ejemplo), pero no es una fuente de excitación sexual. Las personas trans no se están “poniendo” por presentarse o actuar como verdaderamente son.

Dicho esto, muchas personas que aún no caen en la cuenta de que son trans pueden recurrir a fetiches y fantasías para expresar su género y/o aliviar su disforia. Pueden mantener algunas de estas prácticas durante su transición. No hay que avergonzarse por esto, la forma en que se encuentra satisfacción sexual es asunto suyo. Sin embargo, estas cosas van junto a su género. El sentido de género de una persona trans persiste indefinidamente, no se va cuando vuelven a sus vidas cotidianas.

**Comment by Twipped** [comment]
Content installed into public/gdb/es/euphoria.md
