### ISSUE TITLE
Missing Contextual Information for "Increased Emissions During Climax" for Androgenic Second Puberty 101

### ISSUE THREAD

**Issue by FractureFalcon** [GenderDysphoria/GenderDysphoria.fyi#126]
https://genderdysphoria.fyi/en/second-puberty-masc#increased-emissions-during-climax
In this, the text states the following:
> With the swelling of the prostate comes more prostate fluid. If you weren’t a squirter before, you may become one now.

I am not sure it is common knowledge that the Skene's gland is the analogue of the prostate. I have also not heard of anyone calling it the prostate in AFAB people. Both of these might be due to American-centric views (maybe this is more well-known in other parts of the world?) Regardless, I think it would help this statement make more sense if this connection was explained.

**Comment by Twipped** [comment]
> I think it would help this statement make more sense if this connection was explained.

The paragraph immediately above that associates the two terms.

![image](https://user-images.githubusercontent.com/231157/224522955-f08c5b09-ae39-457d-8dcf-c22c47ac1634.png)

> maybe this is more well-known in other parts of the world?

Indeed, the term "female prostate" was formally accepted as a second name for the Skene's Gland in 2001 by the [Federative International Committee on Anatomical Terminology](https://en.wikipedia.org/wiki/Federative_International_Programme_on_Anatomical_Terminology)
