### ISSUE TITLE
Physical Gender Dysphoria Spanish Translation

### ISSUE THREAD

**Issue by VencesMA** [GenderDysphoria/GenderDysphoria.fyi#13]
### Disforia de Género Física

Todos han escuchado la narrativa de “nacidx en el cuerpo equivocado”. La Disforia Física es una incomodidad sobra la forma del propio cuerpo debido a las características sexuales que presenta. Así que, ¿cuáles son las características de las que estamos hablando aquí?

{!{

<style> .fact-grid h4 { font-weight: 600;grid-row: 1; } .fact-grid li {break-inside: avoid;} @media (min-width: 500px) { .fact-grid { display: grid; grid-template-columns: 1fr 2fr; grid-template-rows: min-content 1fr; grid-column-gap: 1em; font-size: 0.7em; } .fact-grid .two-col { column-count: 2; } } </style>
**Características Sexuales Primarias**
}!}
Las características reproductivas principales que se desarrollan durante el embarazo.

- Gónadas
    - Testículos
    - Ovarios
- Genitales externos
    - Pene
	- Clítoris
	- Escroto
	- Labios vaginales
	- Vulva
- Órganos reproductivos internos
	- Próstata / glándulas uretrales
	- Útero

{!{

**Características Sexuales Secundarias**
}!}
Todas las características del dimorfismo sexual que se desarrollan durante y después de la pubertad como resultado de la exposición a hormonas. En general, todas estas características son casi idénticas en niños y niñas prepubescentes.

- Distribución de la grasa
	- Forma de la cintura, cadera y nalgas
	- Muslos, brazos y espalda
	- Mejillas y línea de la mandíbula
- Masa muscular
	- Cuello, hombros y cuerpo superior
	- Brazos y piernas
	- Abdominal
- Estructura ósea
	- Rango de altura
	- Tamaño de pies y manos
	- Ancho de los hombros
	- Ancho de la caja torácica
	- Grosor y densidad de las extremidades
	- Huesos en frente, cejas, mejillas y mandíbula
	- Ancho de la pelvis
- Textura y tono de la piel
- Tono y resonancia de la voz
- Desarrollo del pecho
- Vello facial
- Vello corporal (excluyendo el de genitales y axilas)
{!{

}!}
{!{

Para tu información
}!}
Los genitales de una persona transgénero en terapia hormonal no se comportan ni remotamente como sus contrapartes cisgénero.
- El Pene Estrogénico se suaviza, las erecciones se vuelven menos pronunciadas, la piel se adelgaza y empieza a transpirar como una pared vaginal. El escroto se suaviza y cambia de color, y el rafe perineal se vuelve más distintivo. Debido al cese de las erecciones aleatorias, el tejido eréctil se atrofiará si no es usado con regularidad, causando que el pene entero se haga más chico con el paso del tiempo. La vibración se vuelve una forma más efectiva de estimulación.
- La Vagina Androgénica se vuelve más seca y propensa a desgarros (la lubricación puede ser un problema). La piel del clítoris se engrosa, y el glande del clítoris crece en longitud y circunferencia debido al inicio de erecciones aleatorias. Los labios se vuelven más gruesos, y usualmente con más vello. El inicio de la TRH usualmente resulta en una sensibilidad extrema del clítoris.

{!{

}!}
Las características primarias solo pueden ser alteradas por medio de intervención quirúrgica. Algunas características secundarias son además viajes de una sola vía y requieren de intervención médica para deshacerlas, es decir, el crecimiento del tejido mamario y el engrosamiento de las cuerdas vocales. El Estrógeno no hace la voz más femenina, la Testosterona no hace que los pechos se encojan (más allá de la pérdida de grasa). Cambios en la estructura ósea (como el alargamiento por la testosterona y el ensanchamiento de las caderas por el estrógeno) solo puede ocurrir previo a la edad de 25 años, mientras el cuerpo sigue desarrollándose.

Algunas características secundarias pueden ser mejoradas quirúrgicamente (Aumento de Pechos, contorneo corporal, masculinización / feminización facial), y algunos no pueden ser cambiados.

La disforia física se manifiesta en múltiples y diferentes formas. Algunas veces es sentida como una especie de fenómeno del miembro fantasma, donde la persona puede sentir sensaciones de un pene o una vagina que no está ahí, un dolor en un útero que no existe, o una sensación de ausencia en el tórax por pechos que no han crecido ahí.

Se puede sentir como una clase de efecto fantasma inverso, cuando la persona está consciente de forma persistente de algo que no debería estar ahí. El cerebro recibe información sensorial que no espera, tal como el peso de los pechos, o la presencia de testículos o de un útero, y esta entrada de información toma prioridad porque no es esperada.

Puede sentirse como horror o repulsión al mirar o tocar los genitales externos, disparando estallidos emocionales o un fuerte deseo de remover el órgano ofensor. Las personas trans AFAB (acrónimo en inglés de persona asignada del sexo femenino al nacer; assigend female at birth) pueden experimentar sentimientos de incongruencia durante la menstruación, o sentir una extraña desconexión de sus ciclos hormonales.

{!{

{{import '~/tweet' ids=(array '1220143004821938176' ) tweets=meta.tweets className="hide-reply" }}
}!}
Se puede manifestar como una compulsión de deshacerse de ciertos rasgos corporales, como afeitarse el vello facial y corporal obsesivamente. Esto también se puede manifestar en la compulsión opuesta, llevando a un cuidado meticuloso de esos rasgos con el objetivo de intentar controlarlos, como mantener una barba perfecta, mantener persistentemente las uñas con manicura y pulidas, o pasar horas en el gimnasio intentando moldear la figura.

Las características físicas indeseables pueden provocar que una persona experimente envidia de aquellas personas que han sido forzadas a remover esas características debido a enfermedades, tal como el cáncer testicular o de mama. Las personas AMAB (acrónimo en inglés de persona asignada del sexo masculino al nacer; assigend male at birth) con disforia genital severa, tienden a desear tener alguna clase de accidente que pudiera ocasionar la pérdida de su pene.

Algunas veces puede simplemente ser un sentimiento de estar mal, que ni siquiera puede atribuirse al género o sexo. Durante la mayor parte de mi vida creía que la razón de que odiara mi cuerpo era por ser gorda. No fue hasta que empecé mi transición que me di cuenta de que no odio mi grasa en lo absoluto, odiaba tener grasa masculina. Las curvas femeninas que la TRH me dio me hizo sentir en mucha más sintonía con mi cuerpo.

{!{

{{import '~/tweet' ids=(array '1184580976581775366' '1184837108919230464' ) tweets=meta.tweets className="hide-reply" }}
}!}
La disforia que unx siente respecto a su cuerpo puede y cambiará a lo largo del tiempo, para mejor o para peor. Las mujeres trans, por ejemplo, pueden iniciar hoy una transición sin sentir ninguna desconexión con sus genitales, pero después encontrar que eso cambia conforme el resto de las fuentes de disforia más prominentes desaparecen, la estimulación cambia, y sus genitales mismos cambian su forma y función. Algunxs pueden asumir que definitivamente necesitarán una cirugía de feminización facial, pero luego de 2 años se dan cuenta de que en realidad están bien con su aspecto. Yo solía ser terriblemente sensible sobre mi pico de viuda, pero ahora que mi cabello ha crecido me encuentro totalmente bien con mi línea de cabello.

Está bien que te des cuenta de que necesitas más o menos, que cuando empezaste.

Está bien si no odias nada sobre tu cuerpo y solo deseas lucir más femenina o masculino.

Está bien si no necesitas una transición médica en lo absoluto. Los sentimientos sobre el cuerpo no son el fin último de una transición.

**Tener disforia física total no es un requerimiento para ser transgénero. AFABs no tienen que odiar su pecho, AMABs no tienen que odiar su pene. La experiencia de cada persona trans es diferente. Todas son válidas.**

#### Problemas de Imagen Corporal Internalizados

El mundo está lleno de mensajes subconscientes acerca de cómo los cuerpos de hombres y mujeres deberían ser. Somos bombardeadxs con publicidad y los medios crean una visión normalizada de lo que es y lo que no es bello. No seas muy gordx, no seas muy flacx, no seas demasiado altx, no seas demasiado bajx, no tengas la barbilla demasiado ancha, no tengas la nariz muy larga, usa maquillaje, pero no uses demasiado, no dejes la casa sin un brasier, pero no dejes que el brasier se vea. Siguen y siguen y siguen, en un constante bombardeo de expectativas de género.

Todxs absorben estos mensajes, y las personas trans internalizan los factores que importan al género con el que se alinean. Las chicas trans crecen mapeando los estándares femeninos en sí mismas, los chicos trans mapean los estándares masculinos en sí mismos, y las personas no binaries frecuentemente internalizan vergüenza alrededor de la androginia. Esto es encima de la vergüenza con la que ya cargan por no cumplir con las expectativas del género al que fueron asignadxs.

¿Cuál es el resultado de todo esto? Kathryn lo expresó perfectamente: 

{!{ {{import '~/tweet' ids=(array '947522372315369472' '947523244948680705' ) tweets=meta.tweets className="grid-row" }} }!}

**Comment by Twipped** [comment]
Content installed into public/gdb/es/physical-dysphoria.md
