### ISSUE TITLE
A problem on tweet quote

### ISSUE THREAD

**Issue by rqnj** [GenderDysphoria/GenderDysphoria.fyi#134]
I found a tweet quote block presenting"missing tweets + number" in the Chinese translation of androgenic second puberty page (雄二青春期 in Chinese, line 170-173). I have no idea on how to fix it, hope you can help if possible.

**Comment by Twipped** [comment]
Was this something you fixed in that PR? It doesn't seem to be broken [on the site](https://genderdysphoria.fyi/zh/%E9%9B%84%E4%BA%8C%E9%9D%92%E6%98%A5%E6%9C%9F#%E6%80%A7%E5%90%B8%E5%BC%95).

**Comment by rqnj** [comment]
No, I haven't fixed that...
![image](https://github.com/GenderDysphoria/GenderDysphoria.fyi/assets/71056518/b203ffb9-5afc-4045-8239-15290bfd1a29)

**Comment by Twipped** [comment]
Turned out there were broken tweets on every version of this page, but they were _different_ broken tweets. Anyway, should be fixed now
