### ISSUE TITLE
Trouble adding Dutch Translations

### ISSUE THREAD

**Issue by MaximevanderSmissen** [GenderDysphoria/GenderDysphoria.fyi#137]
Heya!

Awesome work here!
I'm trying to add a Dutch translation, and having a little bit of trouble doing so.
While I've added quite a few pages already, and running `gulp` or `npm run build` locally allows me to view those pages and the dropdown shows it, there's still a problem.
Whenever I select a language (both on the online version as the locally running one), the menu bar (basically everything in the `_strings.js` file) refuses to update correctly and instead reverts to English for the (new) Dutch language only, all other languages work as expected.

Pull request #136 was created to add the translation, and contains all of my current work, this includes the bug I seem to encounter.
Help with this would be much appreciated!

**Comment by ErdaradunGaztea** [comment]
I might have a bit of time this weekend to help somewhat :)

**Comment by ErdaradunGaztea** [comment]
I can't check it right now, but there seems to be something suspicious about `templates/language-menu.hbs` file -- I think you didn't intend on setting `{{#is page.lang 'pt'}}`, but `{{#is page.lang 'nl'}}`. Aaand it seems that you've used the English original as the basis for translation, unfortunately it doesn't have one certain variable translations do: `lang`. There should be a `"lang": "nl"` in `_concat.json` file and `lang: nl` tag for each `.md` with content.

**Comment by MaximevanderSmissen** [comment]
Good catch on that first one, idk what it does exactly though ; ) (didn't fix it, Spanish had it too and works fine)

The second one did it though, works like a charm now!
Thanks for the help!
