### ISSUE TITLE
Spanish page tag bug

### ISSUE THREAD

**Issue by ErdaradunGaztea** [GenderDysphoria/GenderDysphoria.fyi#138]
There's a typo in `templates/language-menu.hbs` with Spanish having a copy-pasted Portuguese tag for its name; the result is cosmetic, but still:

![obraz](https://github.com/GenderDysphoria/GenderDysphoria.fyi/assets/32573962/8e6c2978-7f2c-40cf-8b6f-9b36e7ed09fd)

I noted it not to forget to fix it this weekend :)

**Comment by ErdaradunGaztea** [comment]
Seems like #136 will fix it, guess it's closeable already.

**Comment by MaximevanderSmissen** [comment]
Aaaah, I was wondering what that tag did XD
Yea, the PR will fix it just fine, just tested that on my local branch

I made it into a separate commit on purpose for easy copying and reverting.
Should someone want this fix to happen sooner, you can just copy the change to a separate PR and I'll revert the commit in mine.
