### ISSUE TITLE
Some header permalinks do not work

### ISSUE THREAD

**Issue by the-blank-x** [GenderDysphoria/GenderDysphoria.fyi#144]
## Examples
- https://genderdysphoria.fyi/en/ (table of contents header has ID `table-of-contents:`, while the permalink points to `#table-of-contents`)
- https://genderdysphoria.fyi/en/social-dysphoria (one of us header has ID `“one-of-us!”`, while the permalink points to `#one-of-us`)

## Additional information

Here, the link that the anchor points to is specifically set, instead of the ID of the header tag that it links to.

https://github.com/GenderDysphoria/GenderDysphoria.fyi/blob/7bf1990f6f0c837f17f984d827023feb281cae7b/build/engines.js#L46-L52

A more proper solution (and thus fix) is to [set the `slugify` parameter](https://www.npmjs.com/package/markdown-it-anchor#user-friendly-urls), as shown:

```js
    .use(mAnchor, {
      slugify,
      permalink: mAnchor.permalink.linkInsideHeader({
        class: 'header-link',
        symbol: '<img src="/images/svg/paragraph.svg">',
        ariaHidden: true,
      }),
    })
```

I am slightly reluctant to make a pull request since I don't know why there is `decodeURIComponent(input)`, hence this issue.

**Comment by Twipped** [comment]
Hmm. The decode uri was added to address a similar issue, but I don't remember specifically which headers were causing the problem. See commit d542e8b23d86489ef39798256f04833830b94e2c

**Comment by the-blank-x** [comment]
It seems like the default slugify function converts strings like "Thinner & Softer Fingernails" to "thinner-%26-softer-fingernails", which, when called with the custom slugify function, turns into "thinner-26-softer-fingernails". The call to decodeURIComponent is probably used to convert "thinner-%26-softer-fingernails" to "thinner-&-softer-fingernails", which becomes slugified into "thinner-softer-fingernails", making the URL nicer.

...but this doesn't change the ID for the header, which is still "thinner-%26-softer-fingernails", not "thinner-softer-fingernails".
