### ISSUE TITLE
historical dysphoria page is broken

### ISSUE THREAD

**Issue by thecocohead** [GenderDysphoria/GenderDysphoria.fyi#15]
Hello-
Whenever I try to access the historical dysphoria page, the site errors out. The error and my client is listed below:

Error:
[Pastebin Link (GitHub doesnt like XML tags)](https://pastebin.com/YEUHptQR)

The HostId seems to change every once in a while, not with each reload.

User Client:
Firefox 78 on Windows 10
Chrome ?? on Android ?? (sorry for the missing version numbers)

**Comment by Twipped** [comment]
Oh my goodness, thank you for telling me this! It appears that it got broken a month ago when @VencesMA was working on the Spanish translation. It's been corrected now, thank you! This has been fixed with 626a35b60aa86944a48a976a53c8b17822f5f9cf
