### ISSUE TITLE
Content Contributions

### ISSUE THREAD

**Issue by certified-person** [GenderDysphoria/GenderDysphoria.fyi#22]
Hi, sorry I had no idea how else to contact y'all (I don't have Twitter)

I would like to make content contributions at some stage as I am some of those narratives the website says it is lacking, but I don't know programming things to know what to do via github; one of my friends who does know how to navigate github said they expected more documentation on here, so couldn't help me much. I'd be happy to email content and have you upload it, or something.

Ideas / suggestions?

Cheers

**Comment by Twipped** [comment]
Sorry for taking so long to reply, I had been forgetting to look at my github email folder.

You can submit content suggestions either via email or just here in the issues board.
