### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by JuliaF1988** [GenderDysphoria/GenderDysphoria.fyi#24]
Hello, I translated the gender dysphoria bible into German. If you like you can add it to your website as link or content.
The Word file can be found here: https://drive.google.com/file/d/1Zx4J5JOgNT9xe_0oxuVPaDH5RIyfu1Xb/view

I already published it on reddit: https://www.reddit.com/r/germantrans/comments/kwcqgq/übersetzung_der_gender_dysphoria_bible/

kind regards,
Julia

**Comment by Twipped** [comment]
Sorry for taking so long to reply to this, I had forgotten to check my github email folder.

Thank you so much! I'm currently working on building a framework for hosting translations on the site, so I'll work on adding this translation.

**Comment by E404NNF** [comment]
How's the progress in the translation framework? I really want to translate it to Arabic

**Comment by ErdaradunGaztea** [comment]
Is this issue closeable now?

**Comment by JuliaF1988** [comment]
yes thank you :)
