### ISSUE TITLE
PDF Adaptation

### ISSUE THREAD

**Issue by mirelurk23** [GenderDysphoria/GenderDysphoria.fyi#30]
Hey!

I'm already working on a PDF adaptation of The Gender Dysphoria Bible, because for a lot of the people I talk to about this topic with, it's a lot easier for them if I were to send them a PDF.

So if it would be beneficial in any way to the site, I'd be more than happy to provide a link to the finished file  putting for up online.

In addition, since this is a living document I'd also be happy to maintain the PDF, if needed.

Thanks,
Lexi

**Comment by Twipped** [comment]
There actually already is a PDF version on the site, but it’s not linked anywhere (I shared it via Twitter).

I’m going to do a revamp of the site navigation, and will be adding a link to it when I do.

**Comment by Twipped** [comment]
PDF download link is now on the dropdown nav
