### ISSUE TITLE
Habitus Broken Link

### ISSUE THREAD

**Issue by Kashomon** [GenderDysphoria/GenderDysphoria.fyi#40]
Was reading the site, and encountered a broken link.

![Screen Shot 2021-04-16 at 12 23 59 PM](https://user-images.githubusercontent.com/417814/115074884-2577b680-9eaf-11eb-8d3b-9f238e605951.png)

I looked through the source, but the source looked correct (I couldn't find "Habitus" or "habitus"), so I'm not sure what the issue is.

**Comment by Twipped** [comment]
Fixed with 9459680d570a3c5f3c3d0c30739f3ad04310ea4b

Thanks for reporting.

**Comment by Twipped** [comment]
Habitus was a page I started writing and then decided didn't fit, so I removed it. Must have missed this line when reverting.
