### ISSUE TITLE
Femme

### ISSUE THREAD

**Issue by kanewolf12** [GenderDysphoria/GenderDysphoria.fyi#50]
Pls replace "femme AFAB" with "fem AFAB" In first bold paragraph of presentational dysphoria. Femme refers specifically to lesbians therefore is misgendering.

**Comment by Twipped** [comment]
Uhh, no, Femme does not specifically refer to lesbians, it describes a style of queer presentation and has long been used outside of exclusively lesbian spaces. Stop gatekeeping.
