### ISSUE TITLE
Weird Wording on Euphoria Page (bridal party or bachelor shower)

### ISSUE THREAD

**Issue by jasminegamedev** [GenderDysphoria/GenderDysphoria.fyi#54]
Hello,

I was reading the Gender Dysphoria Bible, and I noticed some weird wording in the examples section. It gives the example of being able to participate in a bridal party or bachelor shower.
![image](https://user-images.githubusercontent.com/85134947/123974746-19fa3e80-d97a-11eb-9c4f-122c68fd97d4.png)
I don't think Bachelor showers are really a thing as far as I can tell. Was this backwards and supposed to be (bridal shower or bachelor party)?

**Comment by Twipped** [comment]
LOL, I must have been real tired when I wrote that, I'm surprised it lasted this long without anyone commenting on it.
