### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by gjvnq** [GenderDysphoria/GenderDysphoria.fyi#56]
I and a few colleges would like to know if we can make a translation of the *Gender Dysphoria Bible* to Brazilian Portuguese.

**Comment by Twipped** [comment]
Hey, sorry for taking a month to get back to you on this. There is now a guide on the site that explains how you can contribute translations. https://genderdysphoria.fyi/contributing/

**Comment by gjvnq** [comment]
My translation is already at the Physical Dysphoria page.

I also made some changes to how translation linking happens (see commit a3a9e8c061ea060c244e94dd82549729a8735351).

My work is at https://github.com/gjvnq/GenderDysphoria.fyi and the main branch I'm working on is `pt-translation`.

**Comment by Twipped** [comment]
> I also made some changes to how translation linking happens

This is an interesting approach, but it defeats one of the goals I had, which is to have each translation's resources entirely within their language folder. This is also important since whole new pages may be added to the english version that might take months to be replicated in translations (this is one reason the spanish version still is unreleased).

**Comment by gjvnq** [comment]
I made the linking a thing that is configured by a single JSON file with
"sets" of equivalent pages. If no equivalent page is configured for the
current one, the language selector will send the user to the first page of
the selected language.

There can be a bit of UI uncertainty for the user but this might be
solvable by a using some icons or colors.

See:
https://github.com/gjvnq/GenderDysphoria.fyi/blob/pt-translation/translation-links.json

Em qui., 3 de mar. de 2022 22:04, Jocelyn Badgley ***@***.***>
escreveu:

**Comment by gjvnq** [comment]
The merging of pull request #111 closed this issue.
