### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by ErdaradunGaztea** [GenderDysphoria/GenderDysphoria.fyi#68]
Hey, just wanted to give a quick head-up for you and perhaps any Polish-speaking person that our trans team started working through the pages. I (or sb else) will make a pull request after all is good and done, this will take a while. Writing this issue just to make sure that there won't be two competing translations created simultaneously ;)

**Comment by dawid-januszkiewicz** [comment]
@ErdaradunGaztea I'd like to contribute, can I join your translation group?

**Comment by ErdaradunGaztea** [comment]
@dawid-januszkiewicz Damn, I haven't checked my GH for a while there. Yes, yes you can, you're welcome, best if you have Discord, because that's where we coordinate our work. I'm thinking about the best way to share a link with you, I'll try sending it to your GH account, but if you can't find it, then we'll make it work some other way.
