### ISSUE TITLE
English "Living Document" disclaimer on German page

### ISSUE THREAD

**Issue by js-on** [GenderDysphoria/GenderDysphoria.fyi#77]
Although defined in `public/de/_disclaimer.hbs`, on German pages of GDB the English "Living Document" disclaimer from `./public/en/_disclaimer.hbs` is shown. Disclaimer is presented correctly for EN, ES and ZH version of GDB.

![gdfyi](https://user-images.githubusercontent.com/55274241/145379963-005a68a6-3460-4f17-b6a7-6f05e5f3160d.png)

Can't fix this, as GDB doesn't run on my system and I'm not into the codebase ¯_(ツ)_/¯

**Comment by ErdaradunGaztea** [comment]
No worries, it* will be corrected soon, Jocelyn already accepted pull request fixing that (yes, I'm responsible for missing that in the first place).

*) also the bottom text and that one untranslated bit in the intro

**Comment by Twipped** [comment]
Just pushed up the changes, sorry for taking so long to deploy
