### ISSUE TITLE
Clarify meaning of "bi-weekly"

### ISSUE THREAD

**Issue by triplrrr** [GenderDysphoria/GenderDysphoria.fyi#79]
At [Cyclical Period-like Symptoms](https://genderdysphoria.fyi/en/second-puberty-fem#cyclical-period-like-symptoms), the word "bi-weekly" is used, which can mean either twice a week or once every two weeks. This is a significant difference in frequency and warrants further clarification.

**Comment by Twipped** [comment]
Fixed by #80
