### ISSUE TITLE
Side boxes disrupting main text

### ISSUE THREAD

**Issue by ErdaradunGaztea** [GenderDysphoria/GenderDysphoria.fyi#82]
There's a problem that was introduced only recently where flex divs on the side would disrupt main text flow, like that:

![image](https://user-images.githubusercontent.com/32573962/155128278-9ef19645-a20f-4317-b1cb-ea51bf99ea28.png)

As far as I know, this is not the problem on mobile (and when I shrink my window just enough); on the other hand, it's a problem on all browsers I tried: Chrome, Vivaldi & Firefox.

**Comment by Twipped** [comment]
Dammit, I knew I should have tested that change more. Thank you!

**Comment by Twipped** [comment]
Fixed with 773af406d8fc7284fdaccadc117b8ca8eaedf8e9 and 5ecaf378add68ddec24a8f193558677415c17038
