### ISSUE TITLE
Introduction in Spanish

### ISSUE THREAD

**Issue by VencesMA** [GenderDysphoria/GenderDysphoria.fyi#9]
+
> **Trans·ge·ne·ro** - *adjetivo*   
> Denota o se relaciona a una persona cuyo sentido personal de identidad y género no corresponde con el sexo asignado al nacer.

|||<div class="copy markup">|||

Desde que la civilización humana ha existido, ha habido personas cuya experiencia interna de género no se alinea con las características físicas de su cuerpo. La Gala, una clase sacerdotal de género intermedio en el imperio Sumerio, existió hacer cuatro mil quinientos años. Las culturas indígenas de Norte América reconocían [un tercer género](https://es.wikipedia.org/wiki/Tercer_sexo) mucho antes de la colonización europea, y lo hacen hasta nuestros días. El emperador romano Elagabalus (218 A.C.) insistió en ser nombrado como Señora en lugar de Señor, e incluso presentó una recompensa a cualquiera que pudiera llevar a cabo una cirugía de reconstrucción genital.

Sin embargo, y a pesar de esto, el entendimiento moderno de la experiencia transgénero tiene apenas 130 años aproximadamente. Incluso la palabra “transgénero” solo se remonta al año 1965 cuando John Oliven la propuso como una alternativa más precisa al término “transexual” de David Cauldwell (acuñado en 1949), que en sí mismo reemplazó al término “travesti” de Magnus Hirschflied.

Ser transgénero es tener una identidad de género que no corresponde con el género que se asumió que tenías basado en los genitales con los que naciste. Esto puede significar que una persona nacida con un pene es en realidad una chica, que una persona nacida con vulva es de hecho un niño, o que una persona con cualquier configuración genital que no encaje por completo en ninguno de los lados del espectro y es no-binarie.

Una persona trans puede llegar a reconocer esto en cualquier punto de su vida. Algunxs niñxs lo identifican tan pronto como son capaces de comprender el concepto de la diferencia entre sexos, otros no empiezan a sentir nada hasta que da inicio la pubertad, y otros no se dan cuenta de que algo está mal hasta que son adultos. Muchas personas simplemente nunca han sido expuestas a la idea de que su género podría no empatar con su sexo de nacimiento o lo que se siente, así que simplemente han aceptado su destino.

Incluso es más común la percepción de que aun si tienen sentimientos de infelicidad con el género que se les asignó al nacer, creen que esto no es lo mismo que lo que las personas transgénero experimentan. Algunos pueden sentir que el deseo de ser transgénero y acceder a una transición es de alguna forma irrespetuoso hacia las “verdaderas” personas trans, aquellas que de hecho sabían que eran niñas o niños “nacidxs en el cuerpo equivocado”. Estas narrativas de la experiencia transgénero que se han extendido por los medios populares crean una impresión muy falsa de lo que significa ser transgénero y lo que se siente crecer como tal.

Esta experiencia de discontinuidad entre el yo interno y externo, es lo que se puede describir como Disforia de Género. Cada persona trans, sin importar su posición dentro o fuera del binario de género, experimenta alguna forma de Disforia de Género. Este tema tiene un tinte político dentro de las comunidades trans, debido a que diferentes grupos tienen sus propias ideas de lo que es la Disforia de Género, cómo se manifiesta, y qué califica a una persona como trans. Sin embargo, en general este debate es inútil e infructífero, ya que la definición al inicio de esta página abarca el inicio y el final de como se entremezclan estos términos.

El propósito de este sitio es documentar las muchas formas en que la Disforia de Género se manifiesta, así como otros aspectos de la transición de género, con el fin de proveer una guía a aquellxs que se están cuestionando, aquellxs que están empezando, aquellxs que ya están encaminadxs, y aquellxs que simplemente desean ser mejores aliadxs.

|||</div>|||

**Comment by Twipped** [comment]
Content installed into public/gdb/es/index.md
